import { Header } from '../components/molecules/Header';
import { Footer } from '../components/molecules/Footer';

import '../theme/styles.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header links={[]} />
        {children}
        <Footer links={[]} />
      </body>
    </html>
  );
}
