export const aspects = [
  'red',
  'yellow',
  'green',
  'moonWhite',
  'yellow-flickering',
  'green-flickering',
  'two-yellows',
  'two-yellows-flickering',
  'yellow-green',
  'yellow-green-flickering',
  'yellow-moonWhite',
  'yellow-moonWhite-flickering',
  'three-yellows',
];
